services:
  - type: web
    name: knewbeauty-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ADMIN_PASSWORD
        generateValue: true
